### PR TITLE
Adds watcher for all docs rst and md files

### PR DESCRIPTION
**Pull request by pomegranited**
Addresses issue where the `docs` changes proposed by https://github.com/edx/edx-platform/pull/24057 didn't trigger an ADR announcement.

**Author Notes & Concerns**

1. Looks like we need to have all these patterns added to cover all the files and subdirs of the various `docs` dirs in this repo.
1. This introduces overlap with the `decisions` subdirs, because they are all  under `docs`?  Unsure whether I should remove the `decisions` patterns, or leave them be in case `decisions` are ever moved outside of `docs`.

<details><summary>Click to view a full find</summary>

```bash
edx-platform$ find . -type d -name decisions
./lms/djangoapps/grades/docs/decisions
./lms/djangoapps/program_enrollments/docs/decisions
./lms/djangoapps/courseware/docs/decisions
./openedx/core/djangoapps/plugins/docs/decisions
./openedx/core/djangoapps/courseware_api/docs/decisions
./openedx/core/djangoapps/oauth_dispatch/docs/decisions
./openedx/features/course_duration_limits/docs/decisions
./openedx/features/discounts/docs/decisions
./openedx/features/content_type_gating/docs/decisions
./docs/decisions
./common/djangoapps/entitlements/docs/decisions
./common/lib/xmodule/xmodule/docs/decisions

edx-platform$ find . -type d -name docs -exec find {} -name \*.rst \;
./lms/djangoapps/grades/docs/decisions/0002-gradebook-front-end.rst
./lms/djangoapps/grades/docs/decisions/0006-overrides-applied-separately.rst
./lms/djangoapps/grades/docs/decisions/0003-persistent-grades.rst
./lms/djangoapps/grades/docs/decisions/0005-grade-freeze.rst
./lms/djangoapps/grades/docs/decisions/0004-persistent-grade-overrides.rst
./lms/djangoapps/grades/docs/decisions/0001-gradebook-api.rst
./lms/djangoapps/grades/docs/how_tos/README.rst
./lms/djangoapps/grades/docs/how_tos/how-to-regrade-everyone-in-a-course.rst
./lms/djangoapps/program_enrollments/docs/decisions/0001-program-enrollment-data-integrity.rst
./lms/djangoapps/program_enrollments/docs/decisions/0002-matriculation-on-user_social_auth_change.rst
./lms/djangoapps/courseware/docs/decisions/0001-xblock-content-overrides.rst
./lms/djangoapps/courseware/docs/decisions/0004-personalized-relative-dates.rst
./lms/djangoapps/courseware/docs/decisions/0003-permissions-via-bridgekeeper.rst
./lms/djangoapps/courseware/docs/decisions/0002-permissions-via-django-rules.rst
./lms/envs/docs/README.rst
./openedx/core/djangoapps/plugins/docs/decisions/0003-plugin-contexts.rst
./openedx/core/djangoapps/schedules/docs/README.rst
./openedx/core/djangoapps/courseware_api/docs/decisions/0001-record-architecture-decisions.rst
./openedx/core/djangoapps/oauth_dispatch/docs/decisions/0001-record-architecture-decisions.rst
./openedx/core/djangoapps/oauth_dispatch/docs/decisions/0007-include-organizations-in-tokens.rst
./openedx/core/djangoapps/oauth_dispatch/docs/decisions/0006-enforce-scopes-in-LMS-APIs.rst
./openedx/core/djangoapps/oauth_dispatch/docs/decisions/0012-scope-and-filter-for-third-party-auth.rst
./openedx/core/djangoapps/oauth_dispatch/docs/decisions/0003-use-jwt-as-oauth-tokens-remove-openid-connect.rst
./openedx/core/djangoapps/oauth_dispatch/docs/decisions/0004-oauth-dispatch-as-router.rst
./openedx/core/djangoapps/oauth_dispatch/docs/decisions/0005-restricted-application-for-SSO.rst
./openedx/core/djangoapps/oauth_dispatch/docs/decisions/0009-jwt-in-session-cookie.rst
./openedx/core/djangoapps/oauth_dispatch/docs/decisions/0010-csrf-protection.rst
./openedx/core/djangoapps/oauth_dispatch/docs/decisions/0011-scope-filter-support.rst
./openedx/core/djangoapps/oauth_dispatch/docs/decisions/0002-migrate-to-dot.rst
./openedx/core/djangoapps/oauth_dispatch/docs/decisions/0008-use-asymmetric-jwts.rst
./openedx/core/djangoapps/oauth_dispatch/docs/README.rst
./openedx/core/djangoapps/oauth_dispatch/docs/how_tos/testing_manually.rst
./openedx/core/djangoapps/credentials/docs/site_config.rst
./openedx/features/course_duration_limits/docs/decisions/0001-access-messages.rst
./openedx/features/discounts/docs/decisions/0001-determining-discount-location.rst
./openedx/features/content_type_gating/docs/decisions/0002-no-new-track.rst
./openedx/features/content_type_gating/docs/decisions/0001-group-access-overrides.rst
./docs/decisions/0001-courses-in-lms.rst
./docs/decisions/0002-inter-app-apis.rst
./docs/guides/index.rst
./docs/guides/frontend/javascript.rst
./docs/guides/frontend/bootstrap.rst
./docs/guides/frontend/static_assets.rst
./docs/guides/frontend/styling.rst
./docs/guides/testing/testing.rst
./docs/guides/docstrings/docstrings.rst
./docs/guides/docstrings/cms_index.rst
./docs/guides/docstrings/lms_index.rst
./docs/guides/docstrings/common_lib.rst
./docs/guides/docstrings/common_index.rst
./docs/guides/docstrings/common_djangoapps.rst
./docs/guides/guides.rst
./docs/api/index.rst
./common/djangoapps/entitlements/docs/decisions/0001-course-uuid-retrieved-by-api.rst
./common/lib/xmodule/xmodule/docs/decisions/0001-move-due-dates-to-db.rst
./common/lib/xmodule/xmodule/modulestore/docs/index.rst
./common/lib/xmodule/xmodule/modulestore/docs/mixedmodulestore.rst
./common/lib/xmodule/xmodule/modulestore/docs/overview.rst
./common/lib/xmodule/xmodule/modulestore/docs/split-mongo.rst
```
</details>

**Reviewer**

- [ ] @nedbat ?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pomegranited! I've created [OSPR-4590](https://openedx.atlassian.net/browse/OSPR-4590) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by nedbat** [comment]
I'm not sure the people following these announcements want to know about all changes to any docs.  @nasthagiri Opinions?

**Comment by bradenmacdonald** [comment]
@pomegranited @nedbat I don't think we want to watch all `docs`; just ones that involve decisions about architecture, platform direction, etc. My plan was just to add `docs/guides/extension_points.rst` to the existing list.

**Comment by nedbat** [comment]
I didn't think we'd be adding individual documents to the bot configuration.  Maybe this doc should go some place already being notified?

**Comment by bradenmacdonald** [comment]
I suggested that at first, but it didn't seem to fit. I'm open to moving it anywhere; I don't really care, as long as it's easily discoverable and watched by this bot :)

**Comment by pomegranited** [comment]
@nedbat @bradenmacdonald  

> Maybe this doc should go some place already being notified?

How about `docs/decisions` then?  https://github.com/edx/edx-platform/pull/24057 documents the extension points that have been decided for the platform, and so it's arguable that any changes to these points belong there.

**Comment by natabene** [comment]
@pomegranited Thank you for your contribution. @nedbat Do you want to take this?

**Comment by pomegranited** [comment]
Closed in favour of https://github.com/edx/pr_watcher_configuration/commit/da2d1047b3778ee32003087c4f3ffe055c3a8b6b

**Comment by openedx-webhooks** [comment]
@pomegranited Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/pr_watcher_configuration&entry.867055334=https://github.com/edx/pr_watcher_configuration/pull/12&entry.1484655318=https://github.com/pomegranited&entry.752974735=2020-05-27+07:17&entry.1917517419=2020-06-04+21:20&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
